alter table DOCS_OUTGOING_DOCUMENTS add constraint FK_DOCS_OUTGOING_DOCUMENTS_ON_DOC_TYPE foreign key (DOC_TYPE_ID) references DOC_DOCUMENT_TYPE(ID);
create index IDX_DOCS_OUTGOING_DOCUMENTS_ON_DOC_TYPE on DOCS_OUTGOING_DOCUMENTS (DOC_TYPE_ID);
