alter table DOCS_OUTGOING_DOCUMENTS add constraint FK_DOCS_OUTGOING_DOCUMENTS_ON_SIGNATORY foreign key (SIGNATORY) references DOC_EMPLOYEES(ID);
create index IDX_DOCS_OUTGOING_DOCUMENTS_ON_SIGNATORY on DOCS_OUTGOING_DOCUMENTS (SIGNATORY);
