alter table DOCS_OUTGOING_DOCUMENTS add constraint FK_DOCS_OUTGOING_DOCUMENTS_ON_AUTHOR foreign key (AUTHOR) references DOC_EMPLOYEES(ID);
create index IDX_DOCS_OUTGOING_DOCUMENTS_ON_AUTHOR on DOCS_OUTGOING_DOCUMENTS (AUTHOR);
