alter table DOCS_OUTGOING_DOCUMENTS add constraint FK_DOCS_OUTGOING_DOCUMENTS_ON_INITIATOR foreign key (INITIATOR_ID) references DOC_EMPLOYEES(ID);
create index IDX_DOCS_OUTGOING_DOCUMENTS_ON_INITIATOR on DOCS_OUTGOING_DOCUMENTS (INITIATOR_ID);
