alter table DOC_EMPLOYEES add constraint FK_DOC_EMPLOYEES_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table DOC_EMPLOYEES add constraint FK_DOC_EMPLOYEES_ON_SUBDIVISION foreign key (SUBDIVISION_ID) references DOC_SUBDIVISIONS(ID);
alter table DOC_EMPLOYEES add constraint FK_DOC_EMPLOYEES_ON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID);
create index IDX_DOC_EMPLOYEES_ON_USER on DOC_EMPLOYEES (USER_ID);
create index IDX_DOC_EMPLOYEES_ON_SUBDIVISION on DOC_EMPLOYEES (SUBDIVISION_ID);
create index IDX_DOC_EMPLOYEES_ON_PHOTO on DOC_EMPLOYEES (PHOTO_ID);
