alter table DOC_SUBDIVISIONS add constraint FK_DOC_SUBDIVISIONS_ON_SUBDIVISIONS foreign key (SUBDIVISIONS_ID) references DOC_SUBDIVISIONS(ID);
create index IDX_DOC_SUBDIVISIONS_ON_SUBDIVISIONS on DOC_SUBDIVISIONS (SUBDIVISIONS_ID);
